// Road closures & hazards slide — merges three sources into #roads-body:
//   MANUAL — `closures` sheet tab (parades, second lines, flooded streets)
//   511    — data/closures-auto.json, produced by the closures.yml cron
//            from the 511LA Events API (same-origin, no CORS)
//   DOTD   — Louisiana DOTD WZDx work-zone feed (CC0, CORS-open),
//            fetched client-side and filtered to the response-area bbox
// Each source refreshes on its own cadence; any refresh re-renders the
// merged list. Severity sorts closed > caution > info; entries are capped
// with a "+N more" line; the empty state is a visible all-clear.

window.Closures = {
  _manual: [],
  _auto: [],
  _wzdx: [],
  _autoGenerated: null,
  _sevRank: { closed: 0, caution: 1, info: 2 },

  // Whitelist sheet-supplied severity: it becomes part of a className, so
  // anything outside the known set collapses to 'info'.
  _sev: function (v) {
    v = (v || '').toLowerCase();
    return this._sevRank[v] !== undefined ? v : 'info';
  },

  start: function () {
    var self = this;
    var polls = BoardConfig.polls;
    var first = [
      SheetLoader.poll(polls.sheetMs, function () { return self._refreshManual(); }),
      SheetLoader.poll(polls.closuresAutoMs, function () { return self._refreshAuto(); }),
      SheetLoader.poll(polls.wzdxMs, function () { return self._refreshWzdx(); })
    ];
    return Promise.allSettled ? Promise.allSettled(first) : Promise.resolve();
  },

  // ── MANUAL lane (sheet tab) ────────────────────────────────────────

  async _refreshManual() {
    var self = this;
    var res = await SheetLoader.fetchTab('closures',
      ['active', 'severity', 'location']);
    if (res && res.unconfigured) { this._render(); return; }
    if (!res) { this._render(); return; } // keep last parsed rows
    var now = Date.now();
    this._manual = res.rows
      .filter(function (r) { return (r.active || '').toLowerCase() === 'yes'; })
      .filter(function (r) { return r.location; })
      .map(function (r) {
        var starts = Fmt.parseLocal(r.starts);
        var ends = Fmt.parseLocal(r.ends, true);
        return {
          badge: 'MANUAL',
          severity: self._sev(r.severity),
          location: r.location,
          detail: r.detail || '',
          source: r.source || '',
          startsAt: starts ? starts.getTime() : null,
          endsAt: ends ? ends.getTime() : null
        };
      })
      .filter(function (c) { return !c.endsAt || c.endsAt > now; });
    this._manualFetchedAt = res.fetchedAt;
    this._manualFromCache = res.fromCache;
    this._render();
  },

  // ── 511LA lane (repo JSON built by closures.yml) ───────────────────

  async _refreshAuto() {
    var res = await Store.fetchJson('closures-auto',
      BoardConfig.closures.autoUrl, function (d) {
        return d && Array.isArray(d.closures);
      });
    if (!res) { Health.set('511', 'down'); this._render(); return; }
    var payload = res.data;
    if (!payload.generated) {
      // Placeholder file — the 511 pipeline isn't live yet.
      Health.set('511', 'off');
      this._auto = [];
      this._render();
      return;
    }
    this._autoGenerated = Date.parse(payload.generated) || null;
    Health.set('511', res.fromCache ? 'cache' : 'ok', res.fetchedAt);
    var now = Date.now();
    this._auto = payload.closures
      .map(function (c) {
        return {
          badge: '511',
          severity: c.severity === 'closed' ? 'closed' : 'caution',
          location: (c.roadway ? c.roadway + ' ' : '') + (c.location || ''),
          detail: c.description || '',
          startsAt: c.starts ? Date.parse(c.starts) : null,
          endsAt: c.ends ? Date.parse(c.ends) : null
        };
      })
      .filter(function (c) { return !c.endsAt || c.endsAt > now; });
    this._render();
  },

  // ── DOTD WZDx lane (client-side GeoJSON) ───────────────────────────

  async _refreshWzdx() {
    var res = await Store.fetchJson('wzdx',
      BoardConfig.closures.wzdxUrl, function (d) {
        return d && Array.isArray(d.features);
      });
    if (!res) { Health.set('dotd', 'down'); this._render(); return; }
    Health.set('dotd', res.fromCache ? 'cache' : 'ok', res.fetchedAt);
    var self = this;
    var now = Date.now();
    var bbox = BoardConfig.closures.bbox;
    this._wzdx = res.data.features
      .filter(function (f) { return self._inBbox(f.geometry, bbox); })
      .map(function (f) {
        var p = f.properties || {};
        var cd = p.core_details || {};
        var startsAt = p.start_date ? Date.parse(p.start_date) : null;
        var endsAt = p.end_date ? Date.parse(p.end_date) : null;
        var severity = p.vehicle_impact === 'all-lanes-closed' ? 'closed'
          : p.vehicle_impact === 'some-lanes-closed' ? 'caution' : 'info';
        return {
          badge: 'DOTD',
          severity: severity,
          location: (cd.road_names || []).join(', ') +
            (cd.direction && cd.direction !== 'unknown' ? ' ' + cd.direction : ''),
          detail: (cd.description || '').slice(0, 140),
          startsAt: startsAt,
          endsAt: endsAt
        };
      })
      .filter(function (c) {
        return c.location &&
          (!c.startsAt || c.startsAt <= now) &&
          (!c.endsAt || c.endsAt > now);
      });
    this._wzdxFetchedAt = res.fetchedAt;
    this._render();
  },

  _inBbox: function (geometry, bbox) {
    if (!geometry || !geometry.coordinates) return false;
    var found = false;
    var walk = function (node) {
      if (found || !Array.isArray(node)) return;
      if (node.length >= 2 &&
          typeof node[0] === 'number' && typeof node[1] === 'number') {
        var lon = node[0], lat = node[1];
        if (lat >= bbox.latMin && lat <= bbox.latMax &&
            lon >= bbox.lonMin && lon <= bbox.lonMax) found = true;
        return;
      }
      for (var i = 0; i < node.length; i++) walk(node[i]);
    };
    walk(geometry.coordinates);
    return found;
  },

  // ── Merge + render ─────────────────────────────────────────────────

  _render: function () {
    var body = document.getElementById('roads-body');
    var footer = document.getElementById('roads-footer');
    if (!body) return;
    var self = this;
    var now = Date.now();
    var cfg = BoardConfig.closures;
    var el = SheetLoader.el;

    var all = this._manual.concat(this._auto, this._wzdx)
      .filter(function (c) { return !c.endsAt || c.endsAt > now; })
      .sort(function (a, b) {
        var ra = self._sevRank[a.severity] !== undefined ? self._sevRank[a.severity] : 2;
        var rb = self._sevRank[b.severity] !== undefined ? self._sevRank[b.severity] : 2;
        return (ra - rb) || ((b.startsAt || 0) - (a.startsAt || 0));
      });

    // An all-clear is only honest when at least one lane has real data;
    // otherwise say so instead of implying clear roads.
    var anyData = !!(this._manualFetchedAt || this._autoGenerated ||
      this._wzdxFetchedAt);
    if (!all.length) {
      body.replaceChildren(el('div', 'roads-empty', anyData
        ? 'No reported closures in the response area.'
        : 'Road status unavailable.'));
    } else {
      var list = el('div', 'closure-list');
      all.slice(0, cfg.maxEntries).forEach(function (c) {
        var item = el('div', 'closure-item sev-' + c.severity);
        item.appendChild(el('span', 'badge badge-' + c.badge.toLowerCase(), c.badge));
        var text = el('div', 'closure-text');
        var loc = c.location;
        if (c.startsAt && c.startsAt > now) {
          loc += ' · starts ' + Fmt.timeOrDate(c.startsAt);
        }
        text.appendChild(el('div', 'closure-loc', loc));
        var detailBits = [];
        if (c.detail) detailBits.push(c.detail);
        if (c.endsAt) detailBits.push('until ' + Fmt.timeOrDate(c.endsAt));
        if (c.source) detailBits.push('(' + c.source + ')');
        if (detailBits.length) {
          text.appendChild(el('div', 'closure-detail', detailBits.join(' · ')));
        }
        item.appendChild(text);
        list.appendChild(item);
      });
      if (all.length > cfg.maxEntries) {
        list.appendChild(el('div', 'closure-detail',
          '+' + (all.length - cfg.maxEntries) + ' more'));
      }
      body.replaceChildren(list);
    }

    if (footer) {
      var bits = [];
      if (this._manualFetchedAt) {
        var manualBit = 'Manual ' + Fmt.ago(this._manualFetchedAt) +
          (this._manualFromCache ? ' (cached)' : '');
        if (now - this._manualFetchedAt > BoardConfig.staleness.sheetMs) {
          manualBit += ' — STALE';
        }
        bits.push(manualBit);
      }
      if (this._autoGenerated) {
        var s = '511 as of ' + Fmt.time(this._autoGenerated);
        if (now - this._autoGenerated > BoardConfig.staleness.closuresAutoMs) {
          s += ' — STALE';
        }
        bits.push(s);
      }
      if (this._wzdxFetchedAt) {
        bits.push('DOTD ' + Fmt.ago(this._wzdxFetchedAt));
      }
      footer.textContent = bits.join(' · ');
    }
  }
};
